version: '3.8'

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: post
    volumes:
      - postdb_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # Exposing the database on port 5434 externally

  go_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run ./cmd/main.go
    depends_on:
      - database
    ports:
      - "8081:8081"
      - "30043:30043"
    volumes:
      - ./config/config-deployment.yaml:/app/config/config.yaml

volumes:
  postdb_data:
