app_name: post
port: 8081
grpcPort: 30043
activityLogUrl: localhost:8085
userInfoUrl: http://localhost:8080/user/
db:
  host: database
  port: "5432"
  username: youruser
  password: yourpassword
  database: post